server:
  port: 8183
  
spring:  application:    name: db-service
  jpa:    hibernate:      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver    username: sa
    password: sa
  h2:    console:      enabled: true

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka