server:
  port: 8761
  
spring:  application:    name: discovery-server

eureka:  instance:    hostname: localhost
  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka
      
zuul:  host:    connect-timeout-millis: 5000000
    socket-timeout-millis:  5000000
  routes:    order:
      path: /order/**
      service-id: order-api